# Generated by Django 5.1.7 on 2025-05-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
