# Generated by Django 4.2.7 on 2025-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finalPrice',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
