# Generated by Django 4.2.7 on 2025-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
