# Generated by Django 4.2.7 on 2025-12-17 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_prodrating_product_ratingcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratingFeedback',
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
