# Generated by Django 4.2.7 on 2025-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finalPrice',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
