# Generated by Django 4.2.7 on 2025-12-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, default='', help_text='Enter sizes comma separated. Example: S,M,L or 6,7,8,9', max_length=100),
        ),
    ]
