# Generated by Django 4.2.7 on 2025-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='', help_text='Enter sizes comma separated. Example: S,M,L or 6,7,8,9', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter discount in percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Enter MRP on Product'),
        ),
    ]
