# Generated by Django 4.2.7 on 2026-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text='Manually mark product as sold out'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_stocks',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'S': 10, 'M': 5}", null=True),
        ),
    ]
