# Generated by Django 5.2.12 on 2026-04-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_is_sold_out_product_size_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_temp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_temp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
