# Generated by Django 5.2.12 on 2026-04-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_category_product_category_obj_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_obj',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_obj',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_temp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_temp',
        ),
    ]
